<?php

// autoload_namespaces.php generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir).'/Conf';

return array(
    'Zend\\Version\\' => array($vendorDir . '/zendframework/zend-version'),
    'Zend\\Escaper\\' => array($vendorDir . '/zendframework/zend-escaper'),
    'Zend\\Debug\\' => array($vendorDir . '/zendframework/zend-debug'),
    'Symfony\\Component\\Console\\' => array($vendorDir . '/symfony/console'),
);
